### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by ghost** [shftcl/www-issues#1]
At the index page, there is a small typo. "The url will never redirects." Redirect should not end with an 's'.

_"Everything is secured with TLS (SSL). All the time.
The url will never_ **redirects**_.
Pages are mobile friendly. No waste of bandwidth."_

**Comment by nitriques** [comment]
Thanks!

**Comment by nitriques** [comment]
Same here! BTW, what do you think of this project ? Hope it solve the same problem we had.

**Comment by ghost** [comment]
Le projet est vraiment cool en soit, simple et efficace. Le UI est comme je l'aime. Bon travail!

**Comment by nitriques** [comment]
Super! Merci! N'hésite pas si tu as des suggestions pour améliorer la plateforme!
