### ISSUE TITLE
Unable to extract a background gif

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#14]
http://pacmusee.qc.ca/fr/accueil
The logo in the header. Top Left.

Version 1.2.1
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2585.0 Safari/537.36
Referer: https://shft.cl/

**Comment by nitriques** [comment]
http://pacmusee.qc.ca/pac/static/images/pac-brand-logo-pointe-a-calliere.gif ?

Works for me...

**Comment by alexleduc** [comment]
https://www.youtube.com/watch?v=3lhQfWNCgIE&feature=youtu.be

**Comment by nitriques** [comment]
Works for me...

**Comment by alexleduc** [comment]
Shift+Click n'extrait pas l'image, il ouvre le lien du logo en nouvelle fenetre (le lien n'est pas neutralisé)

**Comment by nitriques** [comment]
Works for me... C'est peut-être un conflit avec une autre de tes extensions ??? Peux-tu essayer en les désactivant toutes ?
