### ISSUE TITLE
Not able to extract a background image.

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#15]
The hero in this page:

http://blog.invisionapp.com/teams-tight-deadlines/

Version 1.2.1
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
Referer: https://shft.cl/

**Comment by nitriques** [comment]
Invision is blacklisted.
