### ISSUE TITLE
The "Other Sizes" button doesn't work anymore.

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#16]
Version 1.2.1
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2599.0 Safari/537.36
Referer: https://shft.cl/yp11wh71w

**Comment by nitriques** [comment]
weird...

**Comment by nitriques** [comment]
Looks like it was a google issue, working now.
