### ISSUE TITLE
Share on Pinterest doesnt show the image.

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#17]
Parameter 'image_url' (value https:null) is not a valid URL format.

Version 1.2.1
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2599.0 Safari/537.36
Referer: https://shft.cl/yp11wh71w

**Comment by nitriques** [comment]
Can you please give me the pinterest url in question ? Thanks!

**Comment by alexleduc** [comment]
It happens every time you click on the Pinterest Button from the Shiftclick interface.

**Comment by nitriques** [comment]
Haaaaa :) 

Does this url works ?

https://pinterest.com/pin/create/button/?url=https%3A%2F%2Fshft.cl%2Fyp11wh71w&media=https%3A%2F%2Fshft.cl%2Fimg%2Fe%2Fecx.images-amazon.com-1489939145543077.jpg&description=TEST

**Comment by nitriques** [comment]
I do not have an account, hard to test haha

**Comment by alexleduc** [comment]
Oui ca marche :)

**Comment by nitriques** [comment]
:rocket:

**Comment by nitriques** [comment]
Fixed
