### ISSUE TITLE
DeuxHuitHuit logo blocked by AdBlocker

### ISSUE THREAD

**Issue by ghost** [shftcl/www-issues#2]
The company logo image link on the page of an extracted image is removed by ad block. Specifically because the img tag has the _.ad-img_ class. If you change the **ad** terminology used in the html you will get more traffic to your main website from adblock users.

**Comment by nitriques** [comment]
ooooo! Thanks a lot! We will fix that ASAP!

**Comment by nitriques** [comment]
Has been fixed in our dev build. 1.1.1 will be pushed soon, just check https://shft.cl/version.txt :)

**Comment by nitriques** [comment]
Will `.a-d-img` do the trick ? Could not find anything better ;)

**Comment by ghost** [comment]
Si tu veux tester install "adblock plus" et ouvre la console de dev dans chrome. Tu vas pouvoir voir quelles resources sont "Blocked by client".

**Comment by nitriques** [comment]
ok cool merci!

**Comment by nitriques** [comment]
Il ne faut pas avoir /ad/ dans l'url non plus! :)

**Comment by ghost** [comment]
Aha! excellent c'est bon a savoir! :) Merci

On Fri, Jul 17, 2015 at 10:50 AM, Nicolas Brassard <notifications@github.com
