### ISSUE TITLE
Print Screen : Bad Request

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#21]
URL : http://www.numero.com/fr/accessoires
Error Message: Bad Request.
Version 1.2.2
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
Referer: https://shft.cl/

**Comment by nitriques** [comment]
Works for me... https://shft.cl/q3fkr7y3

Which size of screenshot ?

**Comment by alexleduc** [comment]
Work for me too.
