### ISSUE TITLE
Unable to extract image

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#22]
URL: http://www.awesomescreenshot.com/image/956619/2f71a941cd509d29966598a856f63328

PrintScreen See: http://snag.gy/eMgIu.jpg

Error Message: "Buffer must be PNG, JPEG or SVG"

**Comment by nitriques** [comment]
You are trying to extract image from awesome screenshot ?

**Comment by alexleduc** [comment]
Yes, from the URL http://www.awesomescreenshot.com/image/956619/2f71a941cd509d29966598a856f63328

**Comment by nitriques** [comment]
They've hidden their aws creds behind a redirect... I'll see what can be done.

**Comment by nitriques** [comment]
This is fixed in dev.

**Comment by nitriques** [comment]
This is working now: https://shft.cl/ek334m7qt
