### ISSUE TITLE
Wrong image extracted from Houzz's slideshow

### ISSUE THREAD

**Issue by cgx** [shftcl/www-issues#24]
This is nasty. They use a 1x1 pixel image and set the actual image in the background-image CSS property.

Example: http://www.houzz.com/photos/3391787/Dominique-and-Anne-Marie-industrial-staircase-montreal

**Comment by nitriques** [comment]
Yeah we wanted to detect it but there was same origin policy issues with the canvas. I am open to any suggestion on how to fix this... But I fear server side detection might be the only way.

**Comment by nitriques** [comment]
Hey! I just landed a fix for this. !
