### ISSUE TITLE
Not possible to extract image

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#25]
Version 1.2.2
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
Referer: https://shft.cl/

http://www.nealslavin.com/MAIN-PORTFOLIO/4/caption

**Comment by nitriques** [comment]
It sadly works for me... What did you get ? Nothing ?
