### ISSUE TITLE
The screen shot result is not the screenshot selected zone

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#27]
Source: https://thenounproject.com/tillt/collection/hands/?oq=hand%20&cidx=4&i=60413
Result: https://shft.cl/m3v8u72y

Version 1.2.2
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Referer: https://shft.cl/33v0u7n2

**Comment by nitriques** [comment]
Should be fixed!
