### ISSUE TITLE
Impossible d'extraire sur : http://stokkeaustad.com

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#28]
Sur le homepage, pas possible d'extraires les images. Ca l'annule pas non plus l'action du clique.

Version 1.2.2
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Referer: https://shft.cl/um78r772

**Comment by alexleduc** [comment]
Seems to be the img srcset

**Comment by nitriques** [comment]
Looks to be the same as #29
