### ISSUE TITLE
Unable to extract image from Behance

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#29]
https://www.behance.net/gallery/29480673/Desk-bureau-in-solid-walnut-board

Version 1.2.2
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Referer: https://shft.cl/

**Comment by nitriques** [comment]
Hummm weird source value, must investigate

**Comment by fhamon** [comment]
Works4me is this fixed?

**Comment by nitriques** [comment]
WorksForMe on the dev branch.
