### ISSUE TITLE
Grab canvas based image

### ISSUE THREAD

**Issue by munki-boy** [shftcl/www-issues#3]
Add functionality to grab canvas generated image. This is available with trad. right-click/save as browser behaviour.

**Comment by nitriques** [comment]
+1000

**Comment by nitriques** [comment]
Landed in dev! Was easier than I thought, since data-uri support was already present. Harder part was to find a quick way to discard "empty" canvases (which are often used for hit testing, and on top of the real one).

**Comment by munki-boy** [comment]
Great work, how do I update my plugin to try it out?

**Comment by nitriques** [comment]
Version 1.1.0 of the extension has just been release! Chrome should automatically update it.

Thanks again!
