### ISSUE TITLE
Large PrintScreen : Bad request message

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#31]
Its seems that there is a limit of dimension size. So, i'm not able to make a nice printscreen of a nice website.

Version 1.2.2
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Referer: https://shft.cl/

**Comment by nitriques** [comment]
Would you know the size of the screen shot in pixel ?

**Comment by fhamon** [comment]
I am able to reproduce it every time with a window of 1920 x 974 (1080p minus Windows and Chrome taskbar). Simply take a print screen of roughly 90% of the area to reproduce it. Used this image for my test: https://unsplash.com/?photo=y74zvFZ5mSU

**Comment by nitriques** [comment]
This is working now https://shft.cl/j2okq7ij
