### ISSUE TITLE
The printscreen overlay in the outputed image

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#32]
See → https://shft.cl/ke1a4k79s

Version 1.2.2
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Referer: https://shft.cl/ke1a4k79s

**Comment by nitriques** [comment]
wwwwhhhhhaaaaaaattttt ;) That's cool ! haha
