### ISSUE TITLE
Picture Support

### ISSUE THREAD

**Issue by mtclmn** [shftcl/www-issues#34]
Be cool to have `<picture>` support.

**Comment by nitriques** [comment]
Well, it should already be there and it should try to extract the biggest one :( Can you share the url where the picture is ? Might have to be related to their source configuration.

**Comment by mtclmn** [comment]
Ah, right, sorry for the lack of context – here's a reduced test case.
http://codepen.io/mtclmn/pen/rjxdWv?editors=1000

**Comment by nitriques** [comment]
Confirmed: I get "[shft.cl] Url is not valid. Send aborted".

I'll check this ASAP. Thanks for reporting !

**Comment by nitriques** [comment]
I confirm this is fixed in dev now.

**Comment by nitriques** [comment]
fixed in 1.5.6 (just published!)
