### ISSUE TITLE
Idea: save with actual file name

### ISSUE THREAD

**Issue by dualaudi** [shftcl/www-issues#38]
https://shft.cl/ey2rk07jd

It would be nice if the file could be downloaded using the actual file name (collage-min.jpg) and not  (s.w.org-3029723144202845.jpg)

**Comment by nitriques** [comment]
Thanks for the suggestion. I am not against it.
That being said, original filenames are often ugly tho. Would it be better to use the hash ?

cc @alexleduc @fhamon

**Comment by dualaudi** [comment]
Thank you for replying. My process for using the plugin is usually to find the bg images on WP and optimize then re-upload. I have to rename them the same when I re-upload. 

I can see when you mean if I want a FB/IG/flickr image - it is named with an ugly hash and doesn't matter what it's renamed to.

**Comment by fhamon** [comment]
I checked with @alexleduc and @nitriques and we will add this feature in a future release of Shift Click. The download button will have the original file name and not our version of it.

Thanks for the suggestion @dualaudi  ! 😁

**Comment by dualaudi** [comment]
It looks like you had the naming convention updated to reflect original file but now it's reverted to www.domain.com-95465465132.png

**Comment by dualaudi** [comment]
Any idea on when or if you'll be able to go back tot he "original file" naming upon download?

**Comment by nitriques** [comment]
@dualaudi This is fixed now! Thanks for your patience!
