### ISSUE TITLE
Please delete this picture for safety reasons

### ISSUE THREAD

**Issue by alexavega** [shftcl/www-issues#39]
Twitter user account for @alexavegadiva has been deleted for safety reason.

Please do the same with the picture shown in https://shft.cl/e1cf7cb

Thanks

Version 1.4.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
Referer: https://shft.cl/e1cf7cb

**Comment by fhamon** [comment]
Hi @alexavega the picture has been deleted.

👋
