### ISSUE TITLE
Userscript (Tampermonkey) Support [Enhancements]

### ISSUE THREAD

**Issue by aonphleacs** [shftcl/www-issues#40]
Offer Shift.cl as a userscript for use with Tampermonkey as a way to reduce load on Chrome since packaged extensions take more memory (for some reason).

**Comment by nitriques** [comment]
We do check for memory usage a lot: we do not want to have a big impact on that.

Sadly, we can't provide this as a Tampermonkey, since we use quite a lot of chrome extensions specific API... :( It would require a major refactor in order to be able to do it.
