### ISSUE TITLE
Shift click not working. "Seems like we were unable to contact the server."

### ISSUE THREAD

**Issue by mmcvicar** [shftcl/www-issues#41]
Version 1.4.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.56 Safari/537.36
Referer: https://shft.cl/error/empty-response?s=201

**Comment by jacobziegler** [comment]
I think it's the Chrome update. Colleague had the same issue, now that i've updated I get the same error too. 

[EDIT] Installed Version 71.0.3578.80 (Official Build) (64-bit) and Shift Click is working again. Hope they fix whatever is causing the issue.

**Comment by nitriques** [comment]
@jacobziegler Thanks for the heads up. Looks like Chrome 73 did changes how extensions can post to external websites. From https://www.chromestatus.com/feature/5629709824032768

Chrome 73 changes to cross-origin requests in chrome extension content scripts are described at https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

You should see this message in the console.

> content.js:297 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://shft.cl/new with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

We fill this ASAP.

**Comment by nitriques** [comment]
@mmcvicar @jacobziegler Version 1.5.0 of the extension has been publish and should solve the issue. thanks again.

**Comment by jacobziegler** [comment]
@nitriques great! and thanks for the quick response. Where do I find Version 1.5.0? I can only see 1.4.1 in Chrome Store.

**Comment by nitriques** [comment]
@jacobziegler The extension should update as soon as Google publishes it. Sadly, the publish is still in progress. Sorry, we do not control this delay :(

**Comment by jacobziegler** [comment]
@nitriques no worries!

**Comment by nitriques** [comment]
@jacobziegler :+1: It is up :1st_place_medal: You can go to chrome://extensions et hit that "update" button ! Thanks again!
