### ISSUE TITLE
Unable to load image 

### ISSUE THREAD

**Issue by Tasch1015** [shftcl/www-issues#42]
Version 1.4.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Referer: https://shft.cl/error/fatal

**Comment by nitriques** [comment]
Hi @Tasch1015 

We released a new version yesterday, can you try again please ?
