### ISSUE TITLE
Shift click fatal error on instagram slider

### ISSUE THREAD

**Issue by mmcvicar** [shftcl/www-issues#43]
Version 1.4.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.28 Safari/537.36
Referer: https://shft.cl/error/fatal

**Comment by dualaudi** [comment]
Same, not working on instagram now.

**Comment by nitriques** [comment]
Hi, sorry for the long delay, but this should be fixed now, with the version 1.5.4 of the extension.

Thanks for reporting, we had a lot of trouble with this one.
