### ISSUE TITLE
Doesn't work on instagram anymore.

### ISSUE THREAD

**Issue by ouipierreange** [shftcl/www-issues#44]
Version 1.4.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Referer: https://shft.cl/error/fatal

**Comment by fhamon** [comment]
Hi @ouipierreange 

I was able to reproduce this bug and we are looking for a fix.

I will let you know when this is fixed ! 😁

**Comment by nitriques** [comment]
Hi, sorry for the long delay, but this should be fixed now, with the version 1.5.4 of the extension.

Thanks for reporting, we had a lot of trouble with this one.
