### ISSUE TITLE
Could not download photos from this website

### ISSUE THREAD

**Issue by andyviolin** [shftcl/www-issues#45]
Version 1.4.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Referer: https://shft.cl/error/fatal

**Comment by nitriques** [comment]
Hi @andyviolin 

We released a new version yesterday that must have fix this.

Thank you !
