### ISSUE TITLE
Don't wanna download

### ISSUE THREAD

**Issue by sofievikkelsoe** [shftcl/www-issues#46]
Version 1.4.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Referer: https://shft.cl/error/fatal

**Comment by fhamon** [comment]
Hi @sofievikkelsoe 

Do you still have this issue ?
We released a new version that should resolve this.

Thanks for reaching out! 😁

**Comment by nitriques** [comment]
Hi @sofievikkelsoe 

We released a new version yesterday that must have fix this.

Thank you !
