### ISSUE TITLE
Could not extract a .webp image

### ISSUE THREAD

**Issue by paulwagenblast** [shftcl/www-issues#47]
Tried to download an image from a Grailed listing https://www.grailed.com/listings/8772892-undercover-ss2015-undercover-cuban-links-vibram-creeper-loafers? for a reference image and it could not extract the photo. The source file, when directly downloaded, is a .webp file so maybe this is the issue but I have not had issues with them in the past using Shift Click?

Version 1.4.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Referer: https://shft.cl/error/fatal

**Comment by nitriques** [comment]
Webp are working fine: https://shft.cl/j2okq7ij

And the website you link is also working
https://shft.cl/tx3acm7n5
https://shft.cl/qo3a4m7kv

We released a new version yesterday that must have fix this.

Thank you !
