### ISSUE TITLE
Oops, something went wrong!

### ISSUE THREAD

**Issue by randavictor** [shftcl/www-issues#49]
Version 1.5.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Referer: https://shft.cl/error/fatal

![image](https://user-images.githubusercontent.com/13271288/71258035-e464a600-233d-11ea-959d-6201b71076f5.png)

**Comment by madranet** [comment]
I'm getting this every time now, for about the past week.

````
Version 1.5.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.143 YaBrowser/22.5.0.1916 Yowser/2.5 Safari/537.36
Referer: https://shft.cl/error/fatal
````
