### ISSUE TITLE
shift

### ISSUE THREAD

**Issue by mohamada01** [shftcl/www-issues#54]
Version 1.5.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37
Referer: https://shft.cl/error/fatal

**Comment by nitriques** [comment]
Hi ! Which site are you trying to shift click ? Is it publicly accessible ?
