### ISSUE TITLE
Failure to get image

### ISSUE THREAD

**Issue by CatMean** [shftcl/www-issues#55]
Version 1.5.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Referer: https://shft.cl/error/fatal

**Comment by nitriques** [comment]
Hi ! Can you please share the url of the page containing the image ? Thanks !
