### ISSUE TITLE
Cannot retrieve image

### ISSUE THREAD

**Issue by MildMethod** [shftcl/www-issues#56]
Version 1.5.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Referer: https://shft.cl/error/fatal

Issue site: https://www.houzz.com.au/photos/mountain-view-townhouse-scandinavian-home-office-san-francisco-phvw-vp~6055278

**Comment by nitriques** [comment]
I am not able to reproduce, closing.
