### ISSUE TITLE
Shift click no longer working on Chrome for Mac

### ISSUE THREAD

**Issue by Mela** [shftcl/www-issues#57]
Hi, 
Shift click just stopped working for me on Chrome. Just does nothing. 

Regards,

Mela 
----

Version 1.5.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Referer: https://shft.cl/

**Comment by nitriques** [comment]
Thanks for the report. We've been able to reproduce on _some_ macs as well.
We will look into that

**Comment by nitriques** [comment]
This is why: https://chromestatus.com/feature/5726124632965120

**Comment by Mela** [comment]
Rats. Will there be an fix available or will this kill Shift click?

Regards,

Mela

**Comment by nitriques** [comment]
Hi @Mela 

Fear not, we found a fix and published an update to the extension :)

Once approved by Google, version 1.7.1 should work like the old version. Chrome will update the extension automatically.

Thanks again for the heads up :)

**Comment by Mela** [comment]
Thank you for fixing!

**Comment by nitriques** [comment]
Pleasure ! I'll try to let you know when the new version is available by closing the issue.
We are glad to have great users such as yourself.

**Comment by nitriques** [comment]
Version 1.7.1 is available on the Chrome Web Store ! The issue should now be fixed!
Thanks again.
