### ISSUE TITLE
Image URL schema ("Https") is not valid

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#6]
Version 1.1.1
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2545.0 Safari/537.36
Referer: https://thenounproject.com/search/?q=boots&i=15756

**Comment by nitriques** [comment]
Fix by making the regular expression case insensitive.
