### ISSUE TITLE
Buffer must be GIF, PNG, JPG or SVG

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#8]
http://www.c2montreal.com/fr/conferenciers-2016/

Images webp.
https://fr.wikipedia.org/wiki/WebP

**Comment by nitriques** [comment]
Ref: https://github.com/zhangyuanwei/node-images/issues/59

We could convert webp to jpeg by drawing them to a local canvas....

**Comment by nitriques** [comment]
This should be fixed in dev

**Comment by nitriques** [comment]
It is working now https://shft.cl/lv32km7y7
