### ISSUE TITLE
SVG extraction problem on Canary, no error message

### ISSUE THREAD

**Issue by alexleduc** [shftcl/www-issues#9]
https://thenounproject.com/term/team/195236/

Version 1.2.1
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Referer: https://shft.cl/

**Comment by alexleduc** [comment]
Not working on chrome now... :(

**Comment by nitriques** [comment]
Error in console ??

**Comment by alexleduc** [comment]
Nop...

**Comment by nitriques** [comment]
Fixed.
